spring:
  datasource:
    url: jdbc:postgresql://op-db:5432/op_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

euprava:
  zdravstvo:
    # Override base-url-a za razmenu #4 unutar docker mreže.
    base-url: http://zdravstvo:8080
